Feat/sidebar mobile
VaultShield/frontend pull request #50
Opened 2024-05-06 09:18 UTC by BustaGraphic

## TICKET

[Mover sidebar abajo en formato movil
](https://trello.com/c/70t1SWmW/56-mover-sidebar-abajo-en-formato-movil)

## Description

Agregue el sidebar a la versión móvil con sus respectivas funciones

## Evidence:

![image](https://github.com/VaultShield/frontend/assets/147419947/1178915c-dab0-4733-8b85-908a9dbb4c5a)
![image](https://github.com/VaultShield/frontend/assets/147419947/bc379baa-be91-4a04-9fb7-0718a9faea9d)

![image](https://github.com/VaultShield/frontend/assets/147419947/387015a9-282a-410d-ba27-70daf216a106)

2024-05-06 11:59 UTC, Othamae requested changes
En formato movil han dejado de funcionar algunos botones/inputs (por ejemplo del generador, de settings y de las cards de credenciales).
Puede que por algún z-index.
Te pongo un vídeo para que veas a lo que me refiero.  



https://github.com/VaultShield/frontend/assets/90536006/03e6276f-731d-4efa-baeb-3fe0d8423878

2024-05-06 14:13 UTC, Maje922 commented
El sidebar tapa la parte de abajo de los componentes, 
https://www.loom.com/share/e990423a7175422c843af24fa0eba37a?sid=7912a9d3-a05c-41bb-9e1a-6f9c53ef8bb4

2024-05-07 15:49 UTC, Maje922 approved these changes

2024-05-07 15:50 UTC, Maje922 approved these changes

2024-05-07 15:50 UTC, Othamae approved these changes

2024-05-07 15:50 UTC, merged